version: '3.8'

services:
  backend:
    build: .                 # ⬅️ исправлено
    container_name: meat-fish-backend
    restart: always
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    command: npm run start:dev
