version: '3.8'

services:
  backend:
    build: ./backend
    container_name: meat-fish-backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    command: npm run start:dev
